# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b919a5beb3f8b1a40a25070df11058da682826925abab069b63693bc3b8c6d9a7d262c7ab5d7817baf756adfb517b51a2964bd0d57be9024d540eb1a9f926ebd

test:
  secret_key_base: 5b05acbb2175dcc89db46bae1845ab965e0f0c9e69d219a25e0570ae0a633d080da71623fd1f706d47323d4a6c71c795f2d2007b33e4cbb7d8a51fa4b29eaad2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
